services:
  primeproperty-next-agent:
    container_name: primeproperty_next_agent
    image: 355355355/primeproperty-next-agent
    restart: on-failure
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - next_network
networks:
  next_network:
    driver: bridge
